Models/OrderDetail.cs
using System;
using System.Collections.Generic;

namespace BookStore.Models;

public partial class OrderDetail
{
    public int BookIsbn { get; set; }

    public int OrderId { get; set; }

    public DateTime? TransactionDate { get; set; }

    public int? Quantity { get; set; }

    public string? Note { get; set; }

    public virtual Book BookIsbnNavigation { get; set; } = null!;

    public virtual OrderInfo Order { get; set; } = null!;
}

Areas/Staff/Controllers/OrderStaffController.cs
using BookStore.Areas.Models.Authentication;
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Globalization;

namespace BookStore.Areas.Staff.Controllers
{
    [Area("Staff")]
    [Route("Staff/Manager/Order")]
    [Authentication]
    [StaffAuthorize]
    public class OrderStaffController : Controller
    {
        private readonly BookStoreContext _context;

        public OrderStaffController(BookStoreContext ctx)
        {
            _context = ctx;
        }

        [Route("")]
        [Route("List")]
        public IActionResult OrderList()
        {
            var lstOrder = _context.OrderInfos.OrderBy(x => x.EmployeeId).ToList();
            return View(lstOrder);
        }

        [Route("Filter")]
        public IActionResult FilterOrder(int daysAgo)
        {
            if (daysAgo == 999)
            {
               return RedirectToAction("OrderList");
            }
            else
            {
                DateTime currentTime = DateTime.Now.AddDays(-daysAgo).Date;
                var lstFilterOrder = _context.OrderInfos
                                   .Where(x => x.OrderDate >= currentTime)
                                   .ToList();
                return View("OrderList", lstFilterOrder);
            }


        }

        [Route("Accept")]
        public IActionResult AcceptOrder(int orderId)
        {
            var order = _context.OrderInfos
                        .Include(o => o.OrderDetails) // Nạp danh sách các chi tiết đơn hàng
                            .ThenInclude(od => od.BookIsbnNavigation)
                        .Where(x => x.Id.Equals(orderId)).FirstOrDefault();
            if (order.Id != orderId)
            {
                return RedirectToAction("OrderList");
            }
            else
            {
                var EmployeeId = HttpContext.Session.GetString("AccountId");
                order.EmployeeId = int.Parse(EmployeeId);
                var lstBookIsbn = order.OrderDetails.Select(item => item.BookIsbn).ToList();
                var booksToUpdate = _context.Books.Where(book => lstBookIsbn.Contains(book.Isbn)).ToList();

                foreach (var item in order.OrderDetails)
                {
                    var book = booksToUpdate.FirstOrDefault(x => x.Isbn == item.BookIsbn);
                    if (book != null)
                    {
                        book.Stock -= (int)item.Quantity;
                    }
                }
                _context.UpdateRange(booksToUpdate);
                _context.Update(order);
                _context.SaveChanges();
                return RedirectToAction("OrderList");

            }

        }

        [Route("{orderId}")]
        public IActionResult OrderDetail(int orderId)
        {
            var order = _context.OrderInfos
                    .Include(o => o.Customer) // Nạp thông tin khách hàng
                    .Include(o => o.OrderDetails) // Nạp danh sách các chi tiết đơn hàng
                        .ThenInclude(od => od.BookIsbnNavigation)
                    .FirstOrDefault(x => x.Id == orderId);
            return View(order);
        }

        [Route("")]
        [Route("ListProduct")]
        public IActionResult ListProduct()
        {
            var lstProduct = _context.Books
                               .AsNoTracking()
                               .Include(categories => categories.BookCategory)
                               .OrderBy(x => x.Isbn)
                               .ToList();
            return View(lstProduct);
        }
    }
}

Areas/Staff/Views/OrderStaff/ListProduct.cshtml
@{
    ViewData["Title"] = "List Product";
    Layout = "~/Areas/Staff/Views/Shared/_LayoutDashBroad.cshtml";
}
@section css {
    <!-- page css -->
    <link href="~/admin/assets/vendors/datatables/dataTables.bootstrap.min.css" rel="stylesheet">
}
@model IEnumerable<BookStore.Models.Book>

<div class="page-container">

    <!-- Content Wrapper START -->
    <div class="main-content">
        <div class="page-header">
            <div class="header-sub-title">
                <nav class="breadcrumb breadcrumb-dash">
                    <a class="breadcrumb-item" asp-action="index" asp-controller="OrderStaff"><i class="anticon anticon-home m-r-5"></i>Home</a>
                    <a class="breadcrumb-item" asp-action="ProductList" asp-controller="OrderStaff">Quản Lý Sản Phẩm</a>
                    <span class="breadcrumb-item active" href="#">Danh Sách Sản Phẩm</span>
                </nav>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="table-responsive" style="overflow-x:unset">
                    <table class="table table-hover e-commerce-table" id="data-table">
                        <thead>
                            <tr>
                                <th>Mã Sách</th>
                                <th>Tên Sách</th>
                                <th>Danh Mục</th>
                                <th>Giá</th>
                                <th>Số lượng</th>
                                <th>Trạng thái</th>
                                @* <th>Action</th> *@
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var product in Model)
                            {
                                <tr>
                                    <td>
                                        #@product.Isbn
                                    </td>
                                    <td>
                                        <div class="d-flex align-items-center">
                                            <img class="img-fluid rounded" src="@Url.Content("~/ProductsImages/Images/" + product.PictureThumb)" style="max-width: 60px" alt="">
                                            <h6 class="m-b-0 m-l-10">@product.BookName</h6>
                                        </div>
                                    </td>
                                    <td>@product.BookCategory.Name</td>
                                    <td>@Cart.ConvertToVND((decimal)product.Price)</td>
                                    @if (product.Stock < 1)
                                    {
                                        <td class="text-center"><span class="badge badge-pill badge-danger">0</span></td>
                                    }
                                    else if (product.Stock >= 1 && product.Stock <= 20)
                                    {
                                        <td class="text-center"><span class="badge badge-pill badge-warning">@product.Stock</span></td>
                                    }
                                    else
                                    {
                                        <td class="text-center"><span class="badge badge-pill badge-primary">@product.Stock</span></td>
                                    }

                                    <td>
                                        <div class="d-flex align-items-center">
                                            @if (product.Status < 1)
                                            {
                                                <div class="badge badge-danger badge-dot m-r-10"></div>
                                                <div>Chưa Bán</div>
                                            }
                                            else
                                            {
                                                <div class="badge badge-success badge-dot m-r-10"></div>
                                                <div>Đang Bán</div>
                                            }
                                        </div>
                                    </td>
                                    @* <td>
                                        <button class="btn btn-icon btn-hover btn-sm btn-rounded pull-right">
                                            <a asp-controller="OrderStaff" asp-action="ProductDetail" asp-route-productId="@product.Isbn"><i class="anticon anticon-profile"></i></a>
                                        </button>
                                        <button class="btn btn-icon btn-hover btn-sm btn-rounded pull-right">
                                            <a asp-controller="OrderStaff" asp-action="Edit" asp-route-productId="@product.Isbn"><i class="anticon anticon-edit"></i></a>
                                        </button>
                                        <button class="btn btn-icon btn-hover btn-sm btn-rounded">
                                            <a asp-controller="OrderStaff" asp-action="RemoveProduct" asp-route-productId="@product.Isbn"><i class="anticon anticon-delete"></i></a>
                                        </button>
                                    </td> *@
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- Content Wrapper END -->
    <!-- Footer START -->
    <footer class="footer">
        <div class="footer-content">
            <p class="m-b-0">Copyright © 2019 Theme_Nate. All rights reserved.</p>
            <span>
                <a href="" class="text-gray m-r-15">Term &amp; Conditions</a>
                <a href="" class="text-gray">Privacy &amp; Policy</a>
            </span>
        </div>
    </footer>
    <!-- Footer END -->

</div>

@section Scripts {
    <!-- page js -->
    <!-- page js -->
    <script src="~/admin/assets/vendors/datatables/jquery.dataTables.min.js"></script>
    <script src="~/admin/assets/vendors/datatables/dataTables.bootstrap.min.js"></script>
    <script>
        $('#data-table').DataTable();
    </script>

}

Areas/Staff/Views/OrderStaff/OrderDetail.cshtml
@model BookStore.Models.OrderInfo

@{
    ViewData["Title"] = "OrderDetail";
    Layout = "~/Areas/Staff/Views/Shared/_LayoutDashBroad.cshtml";
}

<div class="page-container">


    <!-- Content Wrapper START -->
    <div class="main-content">
        <div class="page-header">
            <h2 class="header-title">Invoice</h2>
            <div class="header-sub-title">
                <nav class="breadcrumb breadcrumb-dash">
                    <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
                    <a class="breadcrumb-item" href="#">Pages</a>
                    <span class="breadcrumb-item active">Invoice</span>
                </nav>
            </div>
        </div>
        <div class="container">
            <div class="card">
                <div class="card-body">
                    <div id="invoice" class="p-h-30">
                        <div class="m-t-15 lh-2">
                            <div class="inline-block">
                                <img class="img-fluid" src="assets/images/logo/logo.png" alt="">
                                <address class="p-l-10">
                                    <span class="font-weight-semibold text-dark">Enlink, Inc.</span><br>
                                    <span>9498 Harvard Street</span><br>
                                    <span>Fairfield, Chicago Town 06824</span><br>
                                    <abbr class="text-dark" title="Phone">Phone:</abbr>
                                    <span>(123) 456-7890</span>
                                </address>
                            </div>
                            <div class="float-right">
                                <h2>INVOICE</h2>
                            </div>
                        </div>
                        <div class="row m-t-20 lh-2">
                            <div class="col-sm-9">
                                <h3 class="p-l-10 m-t-10">Invoice To:</h3>
                                <address class="p-l-10 m-t-10">
                                    <span class="font-weight-semibold text-dark">@Model.Customer.FullName</span><br>
                                    <span>@Model.Customer.Address</span><br>
                                    <span>@Model.Customer.Phone</span>
                                </address>
                            </div>
                            <div class="col-sm-3">
                                <div class="m-t-80">
                                    <div class="text-dark text-uppercase d-inline-block">
                                        <span class="font-weight-semibold text-dark">Invoice No :</span>
                                    </div>
                                    <div class="float-right">#@Model.Id</div>
                                </div>
                                <div class="text-dark text-uppercase d-inline-block">
                                    <span class="font-weight-semibold text-dark">Date :</span>
                                </div>
                                <div class="float-right">@Model.OrderDate</div>
                            </div>
                        </div>
                        <div class="m-t-20">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>No.</th>
                                            <th>Items</th>
                                            <th>Quantity</th>
                                            <th>Price</th>
                                            <th>Total</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.OrderDetails)
                                        {
                                            int index = 1;
                                            <tr>
                                                <th>@index</th>
                                                <td>@item.BookIsbnNavigation.BookName</td>
                                                <td>@item.Quantity</td>
                                                <td>@Cart.ConvertToVND((decimal)item.BookIsbnNavigation.Price)</td>
                                                <td>@Cart.ConvertToVND((decimal)(item.Quantity * item.BookIsbnNavigation.Price))</td>
                                            </tr>
                                            index++;
                                        }
                                    </tbody>
                                </table>
                            </div>
                            <div class="row m-t-30 lh-1-8">
                                <div class="col-sm-12">
                                    <div class="float-right text-right">
                                        <p>Shipping Fee: 35,000 VND</p>
                                        <hr>
                                        <h3><span class="font-weight-semibold text-dark">Total :</span> @Cart.ConvertToVND((decimal)Model.TotalPrice)</h3>
                                        <hr>
                                        @if (Model.EmployeeId == null)
                                        {
                                            <a asp-area="Staff" asp-controller="OrderStaff" asp-action="AcceptOrder" asp-route-orderId="@Model.Id">
                                                <button class="btn btn-primary m-r-5">Xác nhận đơn hàng</button>
                                            </a>
                                        }
                                        else
                                        {
                                            <button class="btn btn-primary m-r-5" disabled style="background-color: yellow;border-color: yellow; color:black">
                                                Đơn hàng đã được xác nhận
                                            </button>
                                        }

                                    </div>
                                </div>
                            </div>
                            <div class="row m-t-30 lh-2">
                                <div class="col-sm-12">
                                    <div class="border-bottom p-v-20">
                                        <p class="text-opacity"><small>In exceptional circumstances, Financial Services can provide an urgent manually processed special cheque. Note, however, that urgent special cheques should be requested only on an emergency basis as manually produced cheques involve duplication of effort and considerable staff resources. Requests need to be supported by a letter explaining the circumstances to justify the special cheque payment.</small></p>
                                    </div>
                                </div>
                            </div>
                            <div class="row m-v-20">
                                <div class="col-sm-6">
                                    <img class="img-fluid text-opacity m-t-5" width="100" src="assets/images/logo/logo.png" alt="">
                                </div>
                                <div class="col-sm-6 text-right">
                                    <small><span class="font-weight-semibold text-dark">Phone:</span> (123) 456-7890</small>
                                    <br>
                                    <small>support@themenate.com</small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Content Wrapper END -->

</div>

Areas/Staff/Views/OrderStaff/OrderList.cshtml
@model IEnumerable<BookStore.Models.OrderInfo>

@{
    ViewData["Title"] = "OrderList";
    Layout = "~/Areas/Staff/Views/Shared/_LayoutDashBroad.cshtml";
}
@section css {
    <!-- page css -->
    <link href="~/admin/assets/vendors/datatables/dataTables.bootstrap.min.css" rel="stylesheet">
}

<div class="page-container">

    <!-- Content Wrapper START -->
    <div class="main-content">
        <div class="page-header">
            <div class="header-sub-title">
                <nav class="breadcrumb breadcrumb-dash">
                    <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
                    <a class="breadcrumb-item" href="#">Quản Lý Đơn Hàng</a>
                    <span class="breadcrumb-item active">Danh Sách Đơn Hàng</span>
                </nav>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="row m-b-30">
                    <div class="col-lg-8">
                        <div class="d-md-flex">
                            <div class="m-b-10 m-r-15">
                                @await Component.InvokeAsync("DateListFilter")
                            </div>
                        </div>
                    </div>
                    @* <div class="col-lg-4 text-right">
                        <a asp-action="AddOrder" asp-controller="OrderManager">
                            <button class="btn btn-primary">
                                <i class="anticon anticon-plus-circle m-r-5"></i>
                                <span>Thêm Đơn Hàng</span>
                            </button>
                        </a>
                    </div> *@
                </div>
                <div class="m-t-25">
                    <table id="data-table" class="table">
                        <thead>
                            <tr>
                                <th>Mã Đơn</th>
                                <th>Tổng Tiền</th>
                                <th>Tình Trạng</th>
                                <th>Thời Gian Đặt</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var od in Model)
                            {
                                var isApproved = od.EmployeeId != null;
                                var isChecked = isApproved ? "checked" : "";
                                var statusClass = isApproved ? "btn-success" : "btn-warning";
                                var statusText = isApproved ? "Đã Duyệt" : "Chưa Duyệt";
                                <tr>
                                    <td>#@od.Id</td>
                                    <td>@Cart.ConvertToVND((decimal)od.TotalPrice)</td>
                                    <td><button class="btn @statusClass">@statusText</button></td>
                                    <td>@od.OrderDate</td>
                                    <td>
                                        <a asp-action="OrderDetail" asp-controller="OrderStaff" asp-area="Staff" asp-route-orderId="@od.Id">
                                            <button class="btn btn-primary m-r-5">
                                                Thông Tin Đơn
                                            </button>
                                        </a>
                                    </td>
                                    @* <td>
                                        <div class="form-group d-flex align-items-center">
                                            <div class="switch m-r-10">
                                                <input type="checkbox" id="switch-@od.Id" disabled="@isApproved" @isChecked>
                                                <label for="switch-@od.Id"></label>
                                            </div>
                                            <label>@statusText</label>
                                        </div>
                                    </td> *@
                                </tr>
                            }
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        document.getElementById('selectDate').addEventListener('change', function () {
            var selectedValue = this.value;
            console.log('Selected Value:', selectedValue);

            if (selectedValue == "all") {
                window.location.href = "/Staff/Manager/Order/List";
            }
            // else {
            //     // Tạo URL phù hợp với router
            //     var url = "/Staff/Manager/Order/Filter/" + selectedValue;

            //     $.ajax({
            //         url: url,
            //         method: "get",
            //         data: {
            //             // Điều này là cách bạn truyền dữ liệu tới action FilterProduct
            //             categoryId: selectedValue,
            //         },
            //         success: function (data) {
            //             // Thực hiện các bước xử lý sau khi nhận được kết quả từ action
            //             window.location.href = url;
            //         },
            //         error: function () {
            //             console.log('Truyền data fail');
            //         }
            //     });
            // }

        });

    </script>
    @* <script>
        // Lấy ra checkbox bằng name
        var checkboxes = document.getElementsByName('switch');

        // Đính kèm sự kiện change cho mỗi checkbox
        checkboxes.forEach(function (checkbox) {
            checkbox.addEventListener('change', function () {
                if (this.checked) {
                    console.log('Checkbox ' + this.id + ' đã được chọn.');
                        var url = "/Staff/Manager/Order/Accept";

                        $.ajax({
                            url: url,
                            method: "post",
                            data: {
                                 orderId: this.id,
                            },
                            success: function (data) {
                                // window.location.href = url;
                                console.log(data);
                            },
                            error: function () {
                                console.log('Truyền data fail');
                            }
                        });
                    // Thêm code xử lý khi checkbox được chọn ở đây
                } else {
                    console.log('Checkbox ' + this.id + ' đã bỏ chọn.');
                    // Thêm code xử lý khi checkbox được bỏ chọn ở đây
                }
            });
        });
    </script> *@
    <!-- page js -->
    <script src="~/admin/assets/vendors/datatables/jquery.dataTables.min.js"></script>
    <script src="~/admin/assets/vendors/datatables/dataTables.bootstrap.min.js"></script>
    <script>
        $('#data-table').DataTable();
    </script>
}